## Request timeout
# timeout: 5s

## Customizable templates path
templates:
  - /etc/prometheus-webhook-dingtalk/dingtalk_template.tmpl

## 定义默认的消息格式，当没有特定的消息格式时将使用这些设置
default_message:
  title: '{{ template "legacy.title" . }}'
  text: '{{ template "dingtalk.default.message" . }}'

## Targets, previously was known as "profiles"
targets:
  webhook1:
    url: https://oapi.dingtalk.com/robot/send?access_token=371988d4248ee5fda293215eafe0e3cebd0be8ff637e09002dd296c9594ef5f8
    # secret for signature
    secret: SEC6e73901c63df8262e81bdc284f7c03874238407bcfa7db62247317bfde99c1ba
